// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: geometry.proto

package geometrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Length struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Length_Pt
	//	*Length_Mm
	//	*Length_Cm
	//	*Length_In
	Value         isLength_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Length) Reset() {
	*x = Length{}
	mi := &file_geometry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Length) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Length) ProtoMessage() {}

func (x *Length) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Length.ProtoReflect.Descriptor instead.
func (*Length) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{0}
}

func (x *Length) GetValue() isLength_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Length) GetPt() float64 {
	if x != nil {
		if x, ok := x.Value.(*Length_Pt); ok {
			return x.Pt
		}
	}
	return 0
}

func (x *Length) GetMm() float64 {
	if x != nil {
		if x, ok := x.Value.(*Length_Mm); ok {
			return x.Mm
		}
	}
	return 0
}

func (x *Length) GetCm() float64 {
	if x != nil {
		if x, ok := x.Value.(*Length_Cm); ok {
			return x.Cm
		}
	}
	return 0
}

func (x *Length) GetIn() float64 {
	if x != nil {
		if x, ok := x.Value.(*Length_In); ok {
			return x.In
		}
	}
	return 0
}

type isLength_Value interface {
	isLength_Value()
}

type Length_Pt struct {
	Pt float64 `protobuf:"fixed64,1,opt,name=pt,proto3,oneof"`
}

type Length_Mm struct {
	Mm float64 `protobuf:"fixed64,2,opt,name=mm,proto3,oneof"`
}

type Length_Cm struct {
	Cm float64 `protobuf:"fixed64,3,opt,name=cm,proto3,oneof"`
}

type Length_In struct {
	In float64 `protobuf:"fixed64,4,opt,name=in,proto3,oneof"`
}

func (*Length_Pt) isLength_Value() {}

func (*Length_Mm) isLength_Value() {}

func (*Length_Cm) isLength_Value() {}

func (*Length_In) isLength_Value() {}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Length                `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Top           *Length                `protobuf:"bytes,2,opt,name=top,proto3" json:"top,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_geometry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetLeft() *Length {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Point) GetTop() *Length {
	if x != nil {
		return x.Top
	}
	return nil
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         *Length                `protobuf:"bytes,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        *Length                `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_geometry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{2}
}

func (x *Size) GetWidth() *Length {
	if x != nil {
		return x.Width
	}
	return nil
}

func (x *Size) GetHeight() *Length {
	if x != nil {
		return x.Height
	}
	return nil
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           *Length                `protobuf:"bytes,1,opt,name=top,proto3" json:"top,omitempty"`
	Right         *Length                `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	Bottom        *Length                `protobuf:"bytes,3,opt,name=bottom,proto3" json:"bottom,omitempty"`
	Left          *Length                `protobuf:"bytes,4,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_geometry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_geometry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_geometry_proto_rawDescGZIP(), []int{3}
}

func (x *Rect) GetTop() *Length {
	if x != nil {
		return x.Top
	}
	return nil
}

func (x *Rect) GetRight() *Length {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *Rect) GetBottom() *Length {
	if x != nil {
		return x.Bottom
	}
	return nil
}

func (x *Rect) GetLeft() *Length {
	if x != nil {
		return x.Left
	}
	return nil
}

var File_geometry_proto protoreflect.FileDescriptor

const file_geometry_proto_rawDesc = "" +
	"\n" +
	"\x0egeometry.proto\x12\x10dossier.geometry\"Y\n" +
	"\x06Length\x12\x10\n" +
	"\x02pt\x18\x01 \x01(\x01H\x00R\x02pt\x12\x10\n" +
	"\x02mm\x18\x02 \x01(\x01H\x00R\x02mm\x12\x10\n" +
	"\x02cm\x18\x03 \x01(\x01H\x00R\x02cm\x12\x10\n" +
	"\x02in\x18\x04 \x01(\x01H\x00R\x02inB\a\n" +
	"\x05value\"a\n" +
	"\x05Point\x12,\n" +
	"\x04left\x18\x01 \x01(\v2\x18.dossier.geometry.LengthR\x04left\x12*\n" +
	"\x03top\x18\x02 \x01(\v2\x18.dossier.geometry.LengthR\x03top\"h\n" +
	"\x04Size\x12.\n" +
	"\x05width\x18\x01 \x01(\v2\x18.dossier.geometry.LengthR\x05width\x120\n" +
	"\x06height\x18\x02 \x01(\v2\x18.dossier.geometry.LengthR\x06height\"\xc2\x01\n" +
	"\x04Rect\x12*\n" +
	"\x03top\x18\x01 \x01(\v2\x18.dossier.geometry.LengthR\x03top\x12.\n" +
	"\x05right\x18\x02 \x01(\v2\x18.dossier.geometry.LengthR\x05right\x120\n" +
	"\x06bottom\x18\x03 \x01(\v2\x18.dossier.geometry.LengthR\x06bottom\x12,\n" +
	"\x04left\x18\x04 \x01(\v2\x18.dossier.geometry.LengthR\x04leftB,Z*github.com/hansmi/dossier/proto/geometrypbb\x06proto3"

var (
	file_geometry_proto_rawDescOnce sync.Once
	file_geometry_proto_rawDescData []byte
)

func file_geometry_proto_rawDescGZIP() []byte {
	file_geometry_proto_rawDescOnce.Do(func() {
		file_geometry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geometry_proto_rawDesc), len(file_geometry_proto_rawDesc)))
	})
	return file_geometry_proto_rawDescData
}

var file_geometry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_geometry_proto_goTypes = []any{
	(*Length)(nil), // 0: dossier.geometry.Length
	(*Point)(nil),  // 1: dossier.geometry.Point
	(*Size)(nil),   // 2: dossier.geometry.Size
	(*Rect)(nil),   // 3: dossier.geometry.Rect
}
var file_geometry_proto_depIdxs = []int32{
	0, // 0: dossier.geometry.Point.left:type_name -> dossier.geometry.Length
	0, // 1: dossier.geometry.Point.top:type_name -> dossier.geometry.Length
	0, // 2: dossier.geometry.Size.width:type_name -> dossier.geometry.Length
	0, // 3: dossier.geometry.Size.height:type_name -> dossier.geometry.Length
	0, // 4: dossier.geometry.Rect.top:type_name -> dossier.geometry.Length
	0, // 5: dossier.geometry.Rect.right:type_name -> dossier.geometry.Length
	0, // 6: dossier.geometry.Rect.bottom:type_name -> dossier.geometry.Length
	0, // 7: dossier.geometry.Rect.left:type_name -> dossier.geometry.Length
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_geometry_proto_init() }
func file_geometry_proto_init() {
	if File_geometry_proto != nil {
		return
	}
	file_geometry_proto_msgTypes[0].OneofWrappers = []any{
		(*Length_Pt)(nil),
		(*Length_Mm)(nil),
		(*Length_Cm)(nil),
		(*Length_In)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geometry_proto_rawDesc), len(file_geometry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geometry_proto_goTypes,
		DependencyIndexes: file_geometry_proto_depIdxs,
		MessageInfos:      file_geometry_proto_msgTypes,
	}.Build()
	File_geometry_proto = out.File
	file_geometry_proto_goTypes = nil
	file_geometry_proto_depIdxs = nil
}
