// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: report.proto

package reportpb

import (
	geometrypb "github.com/hansmi/dossier/proto/geometrypb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextMatchGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Byte offsets for start and end of group.
	Start         int32  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int32  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Text          string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextMatchGroup) Reset() {
	*x = TextMatchGroup{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMatchGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMatchGroup) ProtoMessage() {}

func (x *TextMatchGroup) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMatchGroup.ProtoReflect.Descriptor instead.
func (*TextMatchGroup) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *TextMatchGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TextMatchGroup) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TextMatchGroup) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *TextMatchGroup) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sketch node name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Whether a match was found.
	Valid bool `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	// Node bounds.
	Bounds *geometrypb.Rect `protobuf:"bytes,3,opt,name=bounds,proto3" json:"bounds,omitempty"`
	// Searched rectangles until the node was found to be valid or invalid.
	SearchAreas []*geometrypb.Rect `protobuf:"bytes,4,rep,name=search_areas,json=searchAreas,proto3" json:"search_areas,omitempty"`
	// Complete node text.
	Text *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	// Regular expression match groups.
	TextMatchGroups []*TextMatchGroup `protobuf:"bytes,11,rep,name=text_match_groups,json=textMatchGroups,proto3" json:"text_match_groups,omitempty"`
	// Sketch node tags.
	Tags          []string `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *Node) GetBounds() *geometrypb.Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *Node) GetSearchAreas() []*geometrypb.Rect {
	if x != nil {
		return x.SearchAreas
	}
	return nil
}

func (x *Node) GetText() *wrapperspb.StringValue {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *Node) GetTextMatchGroups() []*TextMatchGroup {
	if x != nil {
		return x.TextMatchGroups
	}
	return nil
}

func (x *Node) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based page number.
	Number        int32            `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Size          *geometrypb.Size `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Nodes         []*Node          `protobuf:"bytes,10,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Page) GetSize() *geometrypb.Size {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Page) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pages []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	// Sketch tags.
	Tags          []string `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{3}
}

func (x *Document) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *Document) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\x15dossier.sketch.report\x1a\x0egeometry.proto\x1a\x1egoogle/protobuf/wrappers.proto\"`\n" +
	"\x0eTextMatchGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\xb4\x02\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12.\n" +
	"\x06bounds\x18\x03 \x01(\v2\x16.dossier.geometry.RectR\x06bounds\x129\n" +
	"\fsearch_areas\x18\x04 \x03(\v2\x16.dossier.geometry.RectR\vsearchAreas\x120\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\x04text\x12Q\n" +
	"\x11text_match_groups\x18\v \x03(\v2%.dossier.sketch.report.TextMatchGroupR\x0ftextMatchGroups\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\"}\n" +
	"\x04Page\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12*\n" +
	"\x04size\x18\x02 \x01(\v2\x16.dossier.geometry.SizeR\x04size\x121\n" +
	"\x05nodes\x18\n" +
	" \x03(\v2\x1b.dossier.sketch.report.NodeR\x05nodes\"Q\n" +
	"\bDocument\x121\n" +
	"\x05pages\x18\x01 \x03(\v2\x1b.dossier.sketch.report.PageR\x05pages\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tagsB*Z(github.com/hansmi/dossier/proto/reportpbb\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_report_proto_goTypes = []any{
	(*TextMatchGroup)(nil),         // 0: dossier.sketch.report.TextMatchGroup
	(*Node)(nil),                   // 1: dossier.sketch.report.Node
	(*Page)(nil),                   // 2: dossier.sketch.report.Page
	(*Document)(nil),               // 3: dossier.sketch.report.Document
	(*geometrypb.Rect)(nil),        // 4: dossier.geometry.Rect
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
	(*geometrypb.Size)(nil),        // 6: dossier.geometry.Size
}
var file_report_proto_depIdxs = []int32{
	4, // 0: dossier.sketch.report.Node.bounds:type_name -> dossier.geometry.Rect
	4, // 1: dossier.sketch.report.Node.search_areas:type_name -> dossier.geometry.Rect
	5, // 2: dossier.sketch.report.Node.text:type_name -> google.protobuf.StringValue
	0, // 3: dossier.sketch.report.Node.text_match_groups:type_name -> dossier.sketch.report.TextMatchGroup
	6, // 4: dossier.sketch.report.Page.size:type_name -> dossier.geometry.Size
	1, // 5: dossier.sketch.report.Page.nodes:type_name -> dossier.sketch.report.Node
	2, // 6: dossier.sketch.report.Document.pages:type_name -> dossier.sketch.report.Page
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
